services:
  media-server-app:
    build: .
    # image: ghcr.io/szucsik/jellyfin-media-server-app:0.0.1-MVP
    container_name: media-server-app
    ports:
      - 8800:8800
      - 8801:8801
    volumes:
      - type: bind
        source: ${VOLUME_MOVIE_DIR}
        target: ${VOLUME_MOVIE_TARGET_DIR}
      - type: bind
        source: ${VOLUME_SERIES_DIR}
        target: ${VOLUME_SERIES_TARGET_DIR}
      - type: bind
        source: ${VOLUME_DOWNLOADED_DIR}
        target: ${VOLUME_DOWNLOADED_TARGET_DIR}
      - type: bind
        source: ${VOLUME_PLACEHOLDER_DIR}
        target: ${VOLUME_PLACEHOLDER_TARGET_DIR}
        read_only: true
      - type: bind
        source: ${TORRENT_FILES_LOCATION}
        target: ${TORRENT_FILES_TARGET_LOCATION}
      - type: bind
        source: ${VOLUME_DB_PATH}        # e.g. /home/you/myproject/database.db
        target: /app/database.db
    environment:
      - NCORE_USERNAME=${NCORE_USERNAME}
      - NCORE_PASSWORD=${NCORE_PASSWORD}
      - TORRENT_FILES_LOCATION=${TORRENT_FILES_LOCATION}
      - TORRENT_FILES_TARGET_LOCATION=${TORRENT_FILES_TARGET_LOCATION}
      - VOLUME_SERIES_DIR=${VOLUME_SERIES_TARGET_DIR}
      - VOLUME_MOVIE_DIR=${VOLUME_MOVIE_TARGET_DIR}
      - VOLUME_PLACEHOLDER_TARGET_DIR=${VOLUME_PLACEHOLDER_TARGET_DIR}
      - VOLUME_DOWNLOADED_DIR=${VOLUME_DOWNLOADED_DIR}
      - VOLUME_DOWNLOADED_TARGET_DIR=${VOLUME_DOWNLOADED_TARGET_DIR}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_USER_ID=${JELLYFIN_USER_ID}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - QBITTORRENT_HOST=${QBITTORRENT_HOST}
      - QBITTORRENT_PORT=${QBITTORRENT_PORT}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
    depends_on:
      - jellyfin
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${VOLUME_CONFIG_DIR}:${VOLUME_CONFIG_TARGET_DIR}
      - ${VOLUME_CACHE_DIR}:${VOLUME_CACHE_TARGET_DIR}
      - type: bind
        source: ${VOLUME_MOVIE_DIR}
        target: ${VOLUME_MOVIE_TARGET_DIR}
      - type: bind
        source: ${VOLUME_SERIES_DIR}
        target: ${VOLUME_SERIES_TARGET_DIR}
      - type: bind
        source: ${VOLUME_DOWNLOADED_DIR}
        target: ${VOLUME_DOWNLOADED_TARGET_DIR}
      - type: bind
        source: ${VOLUME_PLACEHOLDER_DIR}
        target: ${VOLUME_PLACEHOLDER_TARGET_DIR}
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: ${VOLUME_CUSTOM_FONTS_DIR}
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'